name: instagram_dumy
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  cloud_firestore: ^4.7.1
  cloud_firestore_web: ^3.5.1
  firebase_auth: ^4.6.3
  firebase_auth_web: ^5.5.1
  firebase_core: ^2.14.0
  firebase_core_web: ^2.5.0
  firebase_storage: ^11.2.1
  firebase_storage_web: ^3.6.1
  flutter:
    sdk: flutter
  flutter_image_compress: ^2.0.3
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.5
  font_awesome_flutter: ^10.4.0
  google_sign_in: ^6.1.0
  image_cropper: ^5.0.0
  image_cropper_for_web: ^3.0.0
  image_picker: ^1.0.1
  image_picker_web: ^3.0.0+1
  intl: ^0.19.0
  provider: ^6.0.5
  shared_preferences: ^2.1.1
  shimmer: ^3.0.0
  sizer: ^2.0.15
  uuid: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
